{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeScreen/0.0.93/composeScreen-0.0.93.module",
    "group": "com.github.Joshaghani.KmpComposeScreen",
    "module": "composeScreen",
    "version": "0.0.93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-wasm-js-0.0.93.klib",
          "url": "composeScreen-wasm-js-0.0.93.klib",
          "size": 413406,
          "sha512": "e1da4fa53e6a126ffc48f55e4d1221a123326c7ccaccf0a5b3e9957060ca51cd1bebca48dad720cfd43b011eddb18a44c7e208c3aab8510f4658b01b02f9c8b9",
          "sha256": "994706db9a414e3dee832f359d4f584a171a7c8911f9d55ed611406b24d1a692",
          "sha1": "7914fe4bd35b56281f87541efa41bd58eef4e85f",
          "md5": "c07aa47bf686a9aeae3d728b823792e8"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-wasm-js-0.0.93.klib",
          "url": "composeScreen-wasm-js-0.0.93.klib",
          "size": 413406,
          "sha512": "e1da4fa53e6a126ffc48f55e4d1221a123326c7ccaccf0a5b3e9957060ca51cd1bebca48dad720cfd43b011eddb18a44c7e208c3aab8510f4658b01b02f9c8b9",
          "sha256": "994706db9a414e3dee832f359d4f584a171a7c8911f9d55ed611406b24d1a692",
          "sha1": "7914fe4bd35b56281f87541efa41bd58eef4e85f",
          "md5": "c07aa47bf686a9aeae3d728b823792e8"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "composeScreen-wasm-js-0.0.93-sources.jar",
          "url": "composeScreen-wasm-js-0.0.93-sources.jar",
          "size": 78058,
          "sha512": "f23031ce52ede24121eeddc56c192aee79ccb07f62d413426266d3c8fe7555989a3d14924f4b25b060bc25d54420051edf60f99bb60c91af16cc9647ee7c9bee",
          "sha256": "0193c2d33f76f16ceb3d12c20773b4d7f46789186f1f0f1101122a10efb02786",
          "sha1": "dbfe7c5612faf8e0a22d55f36be657259a8ac3c9",
          "md5": "863d2e7538772855945b8507e41c0889"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-0.0.93.kotlin_resources.zip",
          "url": "composeScreen-wasm-js-0.0.93-kotlin_resources.kotlin_resources.zip",
          "size": 392,
          "sha512": "d46c03a93b65c38b80f8d72c5eec604e835342643c6d012785252ad1e1f5bbc83d7cb9d6a35de7cf3319de14927f962c89f9d04b5c66356536eb5bbbd75f163b",
          "sha256": "5fad460016dda44c18ba723de08b9cbd04862a7fd12a6d59cd3005b88454c492",
          "sha1": "c37bf1da8cd9f4e31412a8096468fecc1ef8cab5",
          "md5": "8fbf1dcd82042e53cb359994dd02e16c"
        }
      ]
    }
  ]
}
