{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Joshaghani.KmpComposeScreen",
    "module": "composeScreen",
    "version": "0.0.86",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-metadata-0.0.86.jar",
          "url": "composeScreen-0.0.86.jar",
          "size": 78563,
          "sha512": "513c1ed1e557a423a3576045ab10997a58520791cd950533add5ae278214b56b08c651e31a5612ee8f9d3328bc2c262084295e82e2d6a8fa4f9d8862b818f122",
          "sha256": "a88955af5858a79d98ad834fcec4006481809a8896b9d2af0a3f51a9aef9e8df",
          "sha1": "f3d5a4eed7b61e90b3a4de9788fa92de7ce497ce",
          "md5": "4efef028d0fa91552cf4c959788d8034"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "composeScreen-kotlin-0.0.86-sources.jar",
          "url": "composeScreen-0.0.86-sources.jar",
          "size": 77223,
          "sha512": "d33b44a607ce5ec2bc8d696c6894302aabc5d00a8fcc2f77c162681ea0e2f66e2a3e0f07934d2d759bcb34832de676a431834b0dea2d1ad88d536e2e7224f748",
          "sha256": "ab57d82b5bb4a3c13a991a7e507bb8382233c6a876c0491aefe44fba7699f510",
          "sha1": "4286ec65ffaf1482f5e25f3800f49aae041a947e",
          "md5": "ce05f922a7b1808d4fb71b19cccbd6ef"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.86/composeScreen-android-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.86"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.86/composeScreen-android-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.86"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.86/composeScreen-android-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.86/composeScreen-iosarm64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.86/composeScreen-iosarm64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.86/composeScreen-iosarm64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.86/composeScreen-iosarm64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.86/composeScreen-iossimulatorarm64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.86/composeScreen-iossimulatorarm64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.86/composeScreen-iossimulatorarm64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.86/composeScreen-iossimulatorarm64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.86/composeScreen-iosx64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.86/composeScreen-iosx64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.86/composeScreen-iosx64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.86"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.86/composeScreen-iosx64-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.86"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.86/composeScreen-jvm-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.86"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.86/composeScreen-jvm-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.86"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.86/composeScreen-jvm-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.86"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.86/composeScreen-wasm-js-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.86"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.86/composeScreen-wasm-js-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.86"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.86/composeScreen-wasm-js-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.86"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.86/composeScreen-wasm-js-0.0.86.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.86"
      }
    }
  ]
}
