name: Publish KMP Library (0.0.72)

on:
  # وقتی تگ می‌زنی، اتومات منتشر می‌کند؛ مثال: v0.0.72
  push:
    tags: ["v0.0.72"]

  # امکان اجرای دستی از تب Actions
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to GitHub Packages
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish -Pversion=0.0.72