{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeScreen/0.0.93/composeScreen-0.0.93.module",
    "group": "com.github.Joshaghani.KmpComposeScreen",
    "module": "composeScreen",
    "version": "0.0.93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-jvm-0.0.93.jar",
          "url": "composeScreen-jvm-0.0.93.jar",
          "size": 500067,
          "sha512": "af2d74d965040232324987221ae8d816180c40dfacf63101732ce9b16c483b3d0bfe41e6da32ff38de818b81f903abdb0bd986d371ce150438d5c8b2921105b2",
          "sha256": "13eac6dfb688340bec5eb31e2a0ee27b509ce4ad09968b2ca80eb526780a5956",
          "sha1": "70dd5bd885170486e1a39e7c169c8566aae9c08f",
          "md5": "f8a65caffe40a6a8289e661288a4ad94"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-jvm-0.0.93.jar",
          "url": "composeScreen-jvm-0.0.93.jar",
          "size": 500067,
          "sha512": "af2d74d965040232324987221ae8d816180c40dfacf63101732ce9b16c483b3d0bfe41e6da32ff38de818b81f903abdb0bd986d371ce150438d5c8b2921105b2",
          "sha256": "13eac6dfb688340bec5eb31e2a0ee27b509ce4ad09968b2ca80eb526780a5956",
          "sha1": "70dd5bd885170486e1a39e7c169c8566aae9c08f",
          "md5": "f8a65caffe40a6a8289e661288a4ad94"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "composeScreen-jvm-0.0.93-sources.jar",
          "url": "composeScreen-jvm-0.0.93-sources.jar",
          "size": 78004,
          "sha512": "f8b5b54b111fd66123a45116c07b7cd1205abf8982948e1f2105b2e7112077e30ae382a45ec89f9f0b1f661574a7cbe0789398a93c4d8eaabcec49708feec1df",
          "sha256": "603dd3817a85e898e63a0f58af26d4a0dc8dc8abe958cc0a33b2a9d9c92cc508",
          "sha1": "84842854e523715f5a1ec54df360a8f7ff3abad5",
          "md5": "4ceb9d802f1af987fc2b8490d6a4a531"
        }
      ]
    }
  ]
}
