{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Joshaghani.KmpComposeScreen",
    "module": "composeScreen",
    "version": "0.0.93",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-metadata-0.0.93.jar",
          "url": "composeScreen-0.0.93.jar",
          "size": 77561,
          "sha512": "596b37cba9beea47745045eb0c77973bdac45a4941cfc4143b5657704bc0e0d1601d687b73ff41f359a3478880efd0b805b72d87e9fda449fe50df51d79f78e5",
          "sha256": "9870bfd5696195a4528d3a1a68e73600547d6d8545b996d6a71dac0893783703",
          "sha1": "d56c6f98005a1f4604d6b956526566f0bd98468b",
          "md5": "bd34e1e69135abc123c52f865ea45d7e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "composeScreen-kotlin-0.0.93-sources.jar",
          "url": "composeScreen-0.0.93-sources.jar",
          "size": 76118,
          "sha512": "69f7716e0ca16be56ceffbdfc52ac29586726bc5d69ee4e7c3fcb7cbaa4ee2b5f4b4ec870c71ccffd5d7461fac218231bef9842bcccac3e6e1887dd90955ff93",
          "sha256": "930369155a22d93b596ce225f926bf7cc55ce043627db22ce103d133f984acec",
          "sha1": "6ec610f890bd8635bc04cf76e228ebe0c97f03fd",
          "md5": "cdf243a6ee2aceb5a319f37588b0a50a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.93/composeScreen-android-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.93"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.93/composeScreen-android-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.93"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.93/composeScreen-android-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.93/composeScreen-iosarm64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.93/composeScreen-iosarm64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.93/composeScreen-iosarm64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.93/composeScreen-iosarm64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.93/composeScreen-iossimulatorarm64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.93/composeScreen-iossimulatorarm64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.93/composeScreen-iossimulatorarm64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.93/composeScreen-iossimulatorarm64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.93/composeScreen-iosx64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.93/composeScreen-iosx64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.93/composeScreen-iosx64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.93"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.93/composeScreen-iosx64-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.93"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.93/composeScreen-jvm-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.93"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.93/composeScreen-jvm-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.93"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.93/composeScreen-jvm-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.93"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.93/composeScreen-wasm-js-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.93"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.93/composeScreen-wasm-js-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.93"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.93/composeScreen-wasm-js-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.93"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.93/composeScreen-wasm-js-0.0.93.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.93"
      }
    }
  ]
}
