{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeScreen/0.0.86/composeScreen-0.0.86.module",
    "group": "com.github.Joshaghani.KmpComposeScreen",
    "module": "composeScreen",
    "version": "0.0.86",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-iosArm64Main-0.0.86.klib",
          "url": "composeScreen-iosarm64-0.0.86.klib",
          "size": 396407,
          "sha512": "78dd46cb18e2bb3fd8468fec63f6e0eb1f3dcdf37d25b6b459f480a5c91b26f268ff082416113b6369476ec3df484934ac08f8a8a917f8014808776e64341586",
          "sha256": "a2015ce89f1c60c7a11df7810cc3dac71b23f8fd3259aace9bc369736e0db698",
          "sha1": "97449a9ee67f2b56ef24e9af8a216a7bb031c4c1",
          "md5": "361e5dd3ce3f3c720db0798f6f7b6585"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "composeScreen-iosarm64-0.0.86-sources.jar",
          "url": "composeScreen-iosarm64-0.0.86-sources.jar",
          "size": 79199,
          "sha512": "b3b67118053a965dfd339b3e91d89a79ddf5014620ecae94b672089d60d16022351d3b3b89144a32bd38fb3df0f88270a73dc668ffe36371c7402250a0da3ef2",
          "sha256": "e2181284bfc52957376a1f699441c2604e5574c9c8066d3f6b9999bf043ee358",
          "sha1": "37e773fb62e206d790916c76eb3fd4a904fb9d4f",
          "md5": "9b17fb6b6c9eb4eca034b48423955471"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-0.0.86.kotlin_resources.zip",
          "url": "composeScreen-iosarm64-0.0.86-kotlin_resources.kotlin_resources.zip",
          "size": 392,
          "sha512": "0fec1476fb86e2fd6dd83d1ff88ef69273ab706b07f42fc8f779457bb4033f9f9e54c99ad46c76a3cec8a837bcca9b1b84444e84cb530bc39f58c697a03367ac",
          "sha256": "04c68a5823cd28f6ca0a325eb43a6c7251929adb52cd51ffebb36c1dd25dcfed",
          "sha1": "f7c74ca3eeb3738b066eee88887e4828b358b540",
          "md5": "9d1c07f2aedaccc612a5b2df94364e2d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-iosarm64-0.0.86-metadata.jar",
          "url": "composeScreen-iosarm64-0.0.86-metadata.jar",
          "size": 261,
          "sha512": "c4083b76c8cd8a4d5c15d8c1627839f03ff193c77fd17828f14213a76da72603919c723e01b5b57c5c9b841c82680e7bb1d199bb1ae68770e25dc3195f6e20e4",
          "sha256": "c829f5ff6af0ffb22b31a7c20df2296f6d2f95cf53d82c3d28594cdb8c413437",
          "sha1": "02ce4c0ccf5d4da77410d84053826da3aa527d22",
          "md5": "42a8691520edfe0dff5e59c73ac0f02b"
        }
      ]
    }
  ]
}
