{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Joshaghani.KmpComposeScreen",
    "module": "composeScreen",
    "version": "0.0.94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.9.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-metadata-0.0.94.jar",
          "url": "composeScreen-0.0.94.jar",
          "size": 77578,
          "sha512": "3c914b0b9130908d4db6bf984918f2643c40484e5a50fe52a7b0bf730a2d36ac7515c8112335b9e63cd0cd7f6fa1fce1db75b93c9608fac5386fbc8cdb69db23",
          "sha256": "bbd9932167a68f556a6efaec3e23e980ef4dc3036f11f21f1f396c0755b9e39a",
          "sha1": "3600d811439cff74153e995f729d1aa3a3038880",
          "md5": "395af724c08fee80fa705dccf7ddf0ad"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "composeScreen-kotlin-0.0.94-sources.jar",
          "url": "composeScreen-0.0.94-sources.jar",
          "size": 76273,
          "sha512": "ea00f9269f6678bd0a94b068bee459ca5824e013cd3ca4cf6a3f39bdb0bad1c63d5e5fc4e9619891a918d1cceafb0cacadbca6149eea8dee620ce006a64567fc",
          "sha256": "35b3f4c70db9c52e53723748cb4b0faa8f7b07228112565d3eaf653b248d02c1",
          "sha1": "b1fc17cec150b8cd24411e870df950bccc9093d7",
          "md5": "cd1e0d0347473babea4211ffaea3e159"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.94/composeScreen-android-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.94"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.94/composeScreen-android-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.94"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../composeScreen-android/0.0.94/composeScreen-android-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-android",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.94/composeScreen-iosarm64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.94/composeScreen-iosarm64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.94/composeScreen-iosarm64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosarm64/0.0.94/composeScreen-iosarm64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosarm64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.94/composeScreen-iossimulatorarm64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.94/composeScreen-iossimulatorarm64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.94/composeScreen-iossimulatorarm64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iossimulatorarm64/0.0.94/composeScreen-iossimulatorarm64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iossimulatorarm64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.94/composeScreen-iosx64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.94/composeScreen-iosx64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.94/composeScreen-iosx64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.94"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../composeScreen-iosx64/0.0.94/composeScreen-iosx64-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-iosx64",
        "version": "0.0.94"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.94/composeScreen-jvm-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.94"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.94/composeScreen-jvm-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.94"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../composeScreen-jvm/0.0.94/composeScreen-jvm-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-jvm",
        "version": "0.0.94"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.94/composeScreen-wasm-js-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.94"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.94/composeScreen-wasm-js-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.94"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.94/composeScreen-wasm-js-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.94"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../composeScreen-wasm-js/0.0.94/composeScreen-wasm-js-0.0.94.module",
        "group": "com.github.Joshaghani.KmpComposeScreen",
        "module": "composeScreen-wasm-js",
        "version": "0.0.94"
      }
    }
  ]
}
