name: Publish to Maven Central (KMP)

on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK (if androidTarget is present)
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Sanity check OSSRH creds
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" -u "$OSSRH_USERNAME:$OSSRH_PASSWORD" \
            https://s01.oss.sonatype.org/service/local/staging/profiles)
          echo "HTTP=$code"
          test "$code" = "200"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Publish (sign → Sonatype close+release)
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY:     ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew clean \
            publishToSonatype \
            closeAndReleaseSonatypeStagingRepository \
            --no-configuration-cache \
            --stacktrace --no-daemon