name: Publish & Release to Maven Central

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "staging (فقط ایجاد ریلیز در Sonatype) یا release (بستن و انتشار)"
        required: true
        default: "release"
        type: choice
        options: [staging, release]
  push:
    tags:
      - "*"

permissions:
  contents: read

concurrency:
  group: publish-maven-central
  cancel-in-progress: false

jobs:
  publish:
    name: Publish composeScreen
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle (caching)
        uses: gradle/actions/setup-gradle@v4

      - name: Fail on SNAPSHOT versions
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          if grep -E "version\\s*=\\s*\".*-SNAPSHOT\"" gradle.properties build.gradle.kts 2>/dev/null; then
            echo "SNAPSHOT version detected while pushing a tag. Aborting."
            exit 1
          fi

      - name: Assemble & run quick checks
        run: |
          ./gradlew :composeScreen:assembleRelease \
                     :composeScreen:publishToMavenLocal \
                     -x test \
                     --no-daemon --stacktrace

      - name: Publish to Sonatype (staging)
        run: |
          ./gradlew :composeScreen:publishAllPublicationsToMavenCentralRepository \
            -PmavenCentralUsername="${{ secrets.OSSRH_USERNAME }}" \
            -PmavenCentralPassword="${{ secrets.OSSRH_PASSWORD }}" \
            -PsigningInMemoryKey="${{ secrets.SIGNING_KEY }}" \
            -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_PASSWORD }}" \
            --no-daemon --stacktrace

      - name: Close & Release staging repository
        if: ${{ inputs.release_type == 'release' || startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./gradlew :composeScreen:closeAndReleaseMavenCentralStagingRepository \
            -PmavenCentralUsername="${{ secrets.OSSRH_USERNAME }}" \
            -PmavenCentralPassword="${{ secrets.OSSRH_PASSWORD }}" \
            -PsigningInMemoryKey="${{ secrets.SIGNING_KEY }}" \
            -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_PASSWORD }}" \
            --no-daemon --stacktrace