name: Publish & Release to Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # اگر consumer-rules.pro نداری، یک فایل خالی بساز که هشدار از بین بره
      - name: Ensure empty consumer-rules.pro exists
        run: |
          mkdir -p composeScreen
          touch composeScreen/consumer-rules.pro

      - name: Publish to Sonatype (staging via Central Portal)
        run: |
          ./gradlew :composeScreen:publishAllPublicationsToMavenCentralRepository --stacktrace \
            -PmavenCentralUsername="${{ secrets.OSSRH_USERNAME }}" \
            -PmavenCentralPassword="${{ secrets.OSSRH_PASSWORD }}" \
            -PsigningInMemoryKey="${{ secrets.SIGNING_KEY }}" \
            -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_PASSWORD }}"