{
  "formatVersion": "1.1",
  "component": {
    "url": "../../composeScreen/0.0.87/composeScreen-0.0.87.module",
    "group": "com.github.Joshaghani.KmpComposeScreen",
    "module": "composeScreen",
    "version": "0.0.87",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-wasm-js-0.0.87.klib",
          "url": "composeScreen-wasm-js-0.0.87.klib",
          "size": 408545,
          "sha512": "20098d70c2a128d4d407035adc11a695d2fd33fbbe3964cc84fa790a6ebdd9609bfaa77c8e5f3b990b11a65d6d2b7591fc5d0847af910321a8560c9c029f566d",
          "sha256": "dae17ebcd7f432b9f1acb588738b3cbe965b78b6ae7509059cffdf301d3a713d",
          "sha1": "4f0f4100321acadca26a3eb5ba01f7852af81483",
          "md5": "336ec2e4111ce4d1ad46d889f192790d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-wasm-js-0.0.87.klib",
          "url": "composeScreen-wasm-js-0.0.87.klib",
          "size": 408545,
          "sha512": "20098d70c2a128d4d407035adc11a695d2fd33fbbe3964cc84fa790a6ebdd9609bfaa77c8e5f3b990b11a65d6d2b7591fc5d0847af910321a8560c9c029f566d",
          "sha256": "dae17ebcd7f432b9f1acb588738b3cbe965b78b6ae7509059cffdf301d3a713d",
          "sha1": "4f0f4100321acadca26a3eb5ba01f7852af81483",
          "md5": "336ec2e4111ce4d1ad46d889f192790d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "composeScreen-wasm-js-0.0.87-sources.jar",
          "url": "composeScreen-wasm-js-0.0.87-sources.jar",
          "size": 79163,
          "sha512": "0dbc249eeab38fcc08bca71ec8933e134f21d81e7d485b82c411fb0cadc74e14c21c6157cb80bc631f87d403ea1bec93f51fcf1d559161c36b15d927ca148de9",
          "sha256": "d5e84a544cca394548c83c8c0d33065b0196cba13d0378231dd44ffa3a1730c1",
          "sha1": "01de418fe75b79a1217bbcfc92e572abc0e7325d",
          "md5": "08f222c12600e1f5bb617083c000f247"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.chrisbanes.material3",
          "module": "material3-window-size-class-multiplatform",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "composeScreen-0.0.87.kotlin_resources.zip",
          "url": "composeScreen-wasm-js-0.0.87-kotlin_resources.kotlin_resources.zip",
          "size": 392,
          "sha512": "0157eb7d65d2fb41564b02f6cd73f9a014a425441befc4f4831283999ee631f23fa2d99d344d00101ddc45a16f2a54dd8d6fc063f44d6ef81df390514bccebaa",
          "sha256": "f5adbfe03505eaa876b32ff7c9ffbd180ad6859b8c3d90c130793943051b87c2",
          "sha1": "f052ed004cc5524310efb099c81b4a6706cc75c1",
          "md5": "ce6bac7c5d31e7d6728fb4f037a65362"
        }
      ]
    }
  ]
}
